# Generated by Django 4.1.5 on 2023-01-18 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeuTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(to='futebol.jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('timeA_gol', models.IntegerField(default=0)),
                ('timeB_gol', models.IntegerField(default=0)),
                ('timeA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeA', to='futebol.time')),
                ('timeB', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeB', to='futebol.time')),
            ],
        ),
    ]
